### ISSUE TITLE
Namespace not removed 

### ISSUE THREAD

**Issue by emichaf** [eiffel-community/eiffel-easy2use#25]
### Description
./Easy2Use remove XX -n <ns>  do not remove the namespace. 

### Motivation
Add possibility to remove namespace if empty

### Exemplification
./Easy2Use remove XX -n <ns>  do not remove the namespace. 

### Benefits
Cluster could be cluttered with empty namespaces, now this needs to be done manually with kubectl delete ns xx

### Possible Drawbacks
Users might not want to remove empty namespace by default, possibility to add new flag or similar to remove namespace deafult could be false i.e. leave it!

**Comment by m-linner-ericsson** [comment]
Decision to let the user delete the namespace on its own

**Comment by m-linner-ericsson** [comment]
Closing as we let the user delete the namespace on its own
