### ISSUE TITLE
Easy2Use getting started guide might need some more information

### ISSUE THREAD

**Issue by madssander** [eiffel-community/eiffel-easy2use#68]
### Description

Got a error running the command: ./easy2use start -t Docker Eiffel
It could be nice if there inside the documentation could be written that **'docker-compose V2 in Docker Desktop' might need to be _disabled_**, if the user gets the following output:

> $ ./easy2use start -t Docker Eiffel
> 
> 
> ** Easy2Use Target Configuration **
> Target Type: Docker
> Identified Docker Type: Docker for Windows
> HOST: localhost
> 
> ** Easy2Use Bundle Configuration **
> Bundle: Eiffel
> Network: eiffel.0_1
> Command: start
> Do you want to continue (y/n)? y
> Easy2Use: Docker up package service(s): mongodb mongo_seed rabbitmq ei_backend_artifact ei_backend_sourcechange ei_backend_testexecution ei_backend_allevents ei_frontend vici dummy_er remrem_generate remrem_publish er jenkins jenkins_fem nexus
> unexpected character "." in variable name near "mongodb.host=eiffel-mongodb\nmongodb.port=27017\ndatabase.name=eiffel\ncollection.name=events\n"

### Benefits

Other users won't struggle finding the solution themselves.

**Comment by m-linner-ericsson** [comment]
Fixed by #69
