### ISSUE TITLE
Not able to deploy easy2use services on kubernetes(minikube)

### ISSUE THREAD

**Issue by sankar-palanivel** [eiffel-community/eiffel-easy2use#72]
### Description
The Eiffel easy2use setup installation on Kubernetes-v1.22.x (minikube) is failing with these errors

> $ ./easy2use start Eiffel -t Kubernetes -n eiffel
** Easy2Use Target Configuration **
Target Type: Kubernetes
HELM Version: V3
Domainname: mylocalkube
Cluster configfile: /home/infra/.kube/config
Cluster context: minikube
** Easy2Use Bundle Configuration **
Bundle: Eiffel
Namespace: eiffel
Command: start
Do you want to continue (y/n)? y
Easy2Use: Kubernetes install package service(s): mongodb mongo_seed rabbitmq ei_backend_artifact ei_backend_sourcechange ei_backend_testexecution ei_backend_allevents ei_frontend vici dummy_er remrem_generate remrem_publish er jenkins jenkins_fem nexus
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"
Easy2Use: Could not install eiffel-rabbitmq-eiffel
Easy2Use ERROR: Could not install service(s): mongodb mongo_seed rabbitmq ei_backend_artifact ei_backend_sourcechange ei_backend_testexecution ei_backend_allevents ei_frontend vici dummy_er remrem_generate remrem_publish er jenkins jenkins_fem nexus

### Motivation
Some of the helm charts used in easy2use has legacy kubernetes resource API groups defined in it. 

### Exemplification
Not able to install easyuse sandbox setup on Kubernetes (minikube)

### Benefits
Updating the appropriate kubernetes resource API group version in helm charts can allow users to perform easy2use deployment on top of kubernetes

### Possible Drawbacks
N/A

**Comment by e-backmark-ericsson** [comment]
Closing this since #76 is merged
