### ISSUE TITLE
easy2use configure-local-k8s-minikube switch not properly working

### ISSUE THREAD

**Issue by sankar-palanivel** [eiffel-community/eiffel-easy2use#73]
### Description
"./easy2use configure-local-k8s-minikube Eiffel -t Kubernetes" not working properly in local minikube cluster in Linux systems,

- It has duplicate ingress controller (nginx) entries for minikube
- It has legacy/deprecated kubernetes resources entries
- Not required to have a minikube dashboard running as part of local minikube setup

### Motivation
This is blocking users to configure their local minikube setup for Eiffel services deployment

### Exemplification

- "configure-local-k8s-minikube" switch in ./easy2use has improper ingress setup. This is blocking user to access the easy2use service URL's with their Ingress hosts. 
- Legacy kubernetes resource definitions(heapster) not creating all required resources due to compatibility issues

### Benefits
This helps users to have a local minikube k8s cluster with required addons enabled for easy2use setup

**Comment by m-linner-ericsson** [comment]
Solved by https://github.com/eiffel-community/eiffel-easy2use/pull/75
