### ISSUE TITLE
Fix syntax errors in components configurations and improve docs. 

### ISSUE THREAD

**Issue by pef-ericsson** [eiffel-community/eiffel-easy2use#90]
### Description

Docker configurations about ER and REMREM GENERATE contain syntax errors.

### Expected Behavior

The syntax errors shouldn't be there and the deployment of Eiffel via Docker should be successful.

### Steps To Reproduce

Execute the command **"./easy2use start Eiffel -t Docker -e bundles -y"**.

### The version/edition of the Eiffel Protocol used, if applicable

N/A

**Comment by m-linner-ericsson** [comment]
Closing as PR is merged
